slice_name: Total Invoice by Year
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 6__table
  viz_type: pie
  slice_id: 5
  groupby:
  - year
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TotalInvoice
      description: null
      expression: null
      filterable: true
      groupby: true
      id: null
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: TotalInvoice
    optionName: metric_fqf2hwu1e5_xru1o9ktocd
    sqlExpression: null
  adhoc_filters: []
  row_limit: 50000
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: false
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  donut: false
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["year"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalInvoice","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"TotalInvoice","optionName":"metric_fqf2hwu1e5_xru1o9ktocd","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalInvoice","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"TotalInvoice","optionName":"metric_fqf2hwu1e5_xru1o9ktocd","sqlExpression":null},false]],"annotation_layers":[],"row_limit":50000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"6__table","viz_type":"pie","slice_id":5,"groupby":["year"],"metric":{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"TotalInvoice","description":null,"expression":null,"filterable":true,"groupby":true,"id":null,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"TotalInvoice","optionName":"metric_fqf2hwu1e5_xru1o9ktocd","sqlExpression":null},"adhoc_filters":[],"row_limit":50000,"sort_by_metric":true,"color_scheme":"supersetColors","show_labels_threshold":5,"show_legend":false,"label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","show_labels":true,"labels_outside":true,"outerRadius":70,"donut":false,"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: f25fcd97-c5d0-4246-a8bc-78f64873153a
version: 1.0.0
dataset_uuid: 794c5897-e8ef-415b-83d6-db4fa96a97c4
