version: '3'

services: 
  my_superset:
    image: my-superset:latest

    container_name: superset

    volumes:
      - ./volumes:/opt/superset

    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin

    ports:
      - '9091:8088'